### ISSUE TITLE
RC2135- file not found: PUXY	

### ISSUE THREAD

**Issue by whichbuffer** [DanielAvinoam/TheSubZeroProject#5]
I got a error message on SubZeroLoader and I don't understand what is the purpose of PUXY and NKUI ?
and SubZeroDLL works fine on Windows 10 x64 but I can't try Driver because during building of loader it fail.

![Error](https://user-images.githubusercontent.com/42712921/127751614-5fc71d3e-99d5-4c89-830f-572ab72add45.PNG)

**Comment by DanielAvinoam** [comment]
HI,

PUXY and NKUI are the IDs of the loader’s resources (Which will be the DLL
and driver)
If you’re having trouble with the loader you can always load the malware
manually and test everything.

Best regards,
Daniel

בתאריך שבת, 31 ביולי 2021 ב-23:24 מאת Arda Büyükkaya <
***@***.***>:

**Comment by whichbuffer** [comment]
Thanks for replaying me Daniel,

I got the problem and fix it ,accidently "IDR_PUXY1    PUXY" and the Path of Driver not in the same line (my mistake) due to that it pop up error messages lol , but right now I'm getting another error message on "LINK : fatal error LNK1104: cannot open file 'atls.lib'  "

Did you test this Driver on Windows 10 x64 I got blue screen when I install the driver ?

**Comment by whichbuffer** [comment]
All Fixed 👍 

1-) Install Spectre lib  (x64-x86-ARM)
2-) Change PUXY and NKUI Path to your own path
3-) You may need to re build Loader because some time Visual Studio complaining about DLL "NKUI"  not exists

**Comment by whichbuffer** [comment]
Tested On Windows 10 x64: Driver failed to load (Blue Screen Crash) 

I execute Chrome.exe first then use loader now it doesn't give Bleu Screen but loader crashed this time , what do you prefer about OS Is this worked on Win8 or Win7 ? 
![Save](https://user-images.githubusercontent.com/42712921/127765778-62f146d5-6e7b-48ac-a80a-ed84966ce685.PNG)

**Comment by bu-shuo** [comment]
> Tested On Windows 10 x64: Driver failed to load (Blue Screen Crash)
> 
> I execute Chrome.exe first then use loader now it doesn't give Bleu Screen but loader crashed this time , what do you prefer about OS Is this worked on Win8 or Win7 ? ![Save](https://user-images.githubusercontent.com/42712921/127765778-62f146d5-6e7b-48ac-a80a-ed84966ce685.PNG)

I have the same problem. Do you solve it?
